### PR TITLE
Fix ScanExecutorPT exceptions

### LINKED ISSUE #162: ScanExecutorPT fails to run. Throws AccumuloServerException
ScanExecutorPT fails to complete with the following output:

<details open>
<summary>Shell output</summary>

```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.accumulo.core.clientImpl.AccumuloServerException: Error on server thor:9997
	at org.apache.accumulo.testing.performance.util.TestExecutor.lambda$stream$0(TestExecutor.java:52)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.LongPipeline.collect(LongPipeline.java:491)
	at java.base/java.util.stream.LongPipeline.summaryStatistics(LongPipeline.java:468)
	at org.apache.accumulo.testing.performance.tests.ScanExecutorPT.runShortScans(ScanExecutorPT.java:199)
	at org.apache.accumulo.testing.performance.tests.ScanExecutorPT.runTest(ScanExecutorPT.java:109)
	at org.apache.accumulo.testing.performance.impl.PerfTestRunner.main(PerfTestRunner.java:51)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: org.apache.accumulo.core.clientImpl.AccumuloServerException: Error on server thor:9997
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.accumulo.testing.performance.util.TestExecutor.lambda$stream$0(TestExecutor.java:50)
	... 11 more
Caused by: java.lang.RuntimeException: org.apache.accumulo.core.clientImpl.AccumuloServerException: Error on server thor:9997
	at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:185)
	at org.apache.accumulo.core.clientImpl.ScannerIterator.hasNext(ScannerIterator.java:110)
	at com.google.common.collect.Iterators.size(Iterators.java:163)
	at com.google.common.collect.Iterables.size(Iterables.java:126)
	at org.apache.accumulo.testing.performance.tests.ScanExecutorPT.scan(ScanExecutorPT.java:156)
	at org.apache.accumulo.testing.performance.tests.ScanExecutorPT.lambda$runShortScans$1(ScanExecutorPT.java:196)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.accumulo.core.clientImpl.AccumuloServerException: Error on server thor:9997
	at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:324)
	at org.apache.accumulo.core.clientImpl.ScannerIterator.readBatch(ScannerIterator.java:156)
	at org.apache.accumulo.core.clientImpl.ScannerIterator.getNextBatch(ScannerIterator.java:174)
	... 9 more
Caused by: org.apache.thrift.TApplicationException: Internal error processing startScan
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.recv_startScan(TabletClientService.java:249)
	at org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Client.startScan(TabletClientService.java:221)
	at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:453)
	at org.apache.accumulo.core.clientImpl.ThriftScanner.scan(ThriftScanner.java:317)
	... 11 more

```

</details>

<details open>
<summary>Server logs</summary>

```
java.lang.IllegalArgumentException: Invalid option heed_hints at 
org.apache.accumulo.core.spi.scan.SimpleScanDispatcher.lambda$init$0(SimpleScanDispatcher.java:105) at 
com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:185) at 
org.apache.accumulo.core.spi.scan.SimpleScanDispatcher.init(SimpleScanDispatcher.java:81) at 
org.apache.accumulo.server.conf.TableConfiguration.createScanDispatcher(TableConfiguration.java:215) at 
org.apache.accumulo.server.conf.TableConfiguration.lambda$new$1(TableConfiguration.java:82) at 
org.apache.accumulo.core.conf.AccumuloConfiguration$DeriverImpl.derive(AccumuloConfiguration.java:482) at 
org.apache.accumulo.server.conf.TableConfiguration.getScanDispatcher(TableConfiguration.java:270) at 
org.apache.accumulo.tserver.ThriftClientHandler.getScanDispatcher(ThriftClientHandler.java:272) at 
org.apache.accumulo.tserver.ThriftClientHandler.continueScan(ThriftClientHandler.java:378) at 
org.apache.accumulo.tserver.ThriftClientHandler.startScan(ThriftClientHandler.java:342) at 
jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) at 
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at 
java.base/java.lang.reflect.Method.invoke(Method.java:566) at 
org.apache.accumulo.core.trace.TraceUtil.lambda$wrapService$6(TraceUtil.java:235) at 
com.sun.proxy.$Proxy38.startScan(Unknown Source) at 
org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$startScan.getResult(TabletClientService.java:2944) at 
org.apache.accumulo.core.tabletserver.thrift.TabletClientService$Processor$startScan.getResult(TabletClientService.java:2923)
 at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) at 
org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) at 
org.apache.accumulo.server.rpc.TimedProcessor.process(TimedProcessor.java:63) at 
org.apache.thrift.server.AbstractNonblockingServer$FrameBuffer.invoke(AbstractNonblockingServer.java:524) at 
org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer.invoke(CustomNonBlockingServer.java:114) at
 org.apache.thrift.server.Invocation.run(Invocation.java:18) at 
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at 
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at 
java.base/java.lang.Thread.run(Thread.java:829) 
```

</details>

### PR DESCRIPTION
**Pull request by DomGarguilo**
Fixes #162 

* Replace old hint method with new scan_type method of selecting executors

### CODE REVIEW

**Comment by DomGarguilo** [comment]
I'm not certain that these changes are preserving the exact functionality of the old code. Also, there are a few minor changes that I will include in this PR once all fix-related changes are deemed correct as to not clutter the diff.

**Comment by DomGarguilo** [comment]
@keith-turner, it looks like you implemented these changes in https://github.com/apache/accumulo/pull/972 so I was wondering if you might have some thoughts regarding these changes.

File: src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java [hunk 1]
```diff
@@ -201,7 +207,7 @@ private LongSummaryStatistics runShortScans(Environment env, String tableName, i
   }
 
   private TestExecutor<Long> startLongScans(Environment env, String tableName, AtomicBoolean stop) {
-    Map<String,String> hints = ImmutableMap.of("priority", "2");
+    Map<String,String> hints = Map.of("scan_type", "se1p2");
```
Comment (keith-turner) [inline src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java:210]:
```suggestion
    Map<String,String> hints = Map.of("scan_type", "long");
```

File: src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java [hunk 2]
```diff
@@ -178,11 +185,10 @@ private long scan(String tableName, AccumuloClient c, AtomicBoolean stop,
...
   }
 
-  private LongSummaryStatistics runShortScans(Environment env, String tableName, int numScans)
-      throws InterruptedException, ExecutionException {
+  private LongSummaryStatistics runShortScans(Environment env, String tableName, int numScans) {
 
-    Map<String,String> execHints = ImmutableMap.of("executor", "se2");
-    Map<String,String> prioHints = ImmutableMap.of("priority", "1");
+    Map<String,String> execHints = ImmutableMap.of("scan_type", "se2p1");
+    Map<String,String> prioHints = ImmutableMap.of("scan_type", "se1p1");
```
Comment (keith-turner) [inline src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java:191]: Could change the map names and use more descriptive name for the scan types.

```suggestion
    Map<String,String> dHints = ImmutableMap.of("scan_type", "dedicated");
    Map<String,String> sHints = ImmutableMap.of("scan_type", "short");
```

File: src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java [hunk 3]
```diff
@@ -75,10 +74,17 @@ public SystemConfiguration getSystemConfig() {
...
+        Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se1.prioritizer.opts.priority.se1p1", "1");
+    siteCfg.put(
+        Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se1.prioritizer.opts.priority.se1p2", "2");
+
     siteCfg.put(Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se2.threads",
         SCAN_EXECUTOR_THREADS);
     siteCfg.put(Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se2.prioritizer",
         SCAN_PRIORITIZER);
+    siteCfg.put(
+        Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se2.prioritizer.opts.priority.se2p1", "1");
```
Comment (keith-turner) [inline src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java:87]: We can omit this if everything on the se2 pool will have the same prio, then it does not matter what it is. The default would be fine.

```suggestion
```

File: src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java [hunk 4]
```diff
@@ -75,10 +74,17 @@ public SystemConfiguration getSystemConfig() {
         SCAN_EXECUTOR_THREADS);
     siteCfg.put(Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se1.prioritizer",
         SCAN_PRIORITIZER);
+    siteCfg.put(
+        Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se1.prioritizer.opts.priority.se1p1", "1");
+    siteCfg.put(
+        Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se1.prioritizer.opts.priority.se1p2", "2");
+
```
Comment (keith-turner) [inline src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java:81]:
```suggestion
    siteCfg.put(
        Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se1.prioritizer.opts.priority.short", "1");
    siteCfg.put(
        Property.TSERV_SCAN_EXECUTORS_PREFIX.getKey() + "se1.prioritizer.opts.priority.long", "2");

```

**Review by keith-turner — APPROVED** [review]
@DomGarguilo your changes look correct to me.  I made some suggestions to simplify the config and user more descriptive names for scan_type.

**Review by Manno15 — APPROVED** [review]
Changes look good. The test completes as expected. I did notice a few small corrections to make with other parts of the test but I will wait until you push your other changes up just in case they are already handled.

File: src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java [hunk 5]
```diff
@@ -89,8 +95,9 @@ public Report runTest(Environment env) throws Exception {
     String tableName = "scept";
 
     Map<String,String> props = new HashMap<>();
-    props.put(Property.TABLE_SCAN_DISPATCHER_OPTS.getKey() + "executor", "se1");
-    props.put(Property.TABLE_SCAN_DISPATCHER_OPTS.getKey() + "heed_hints", "true");
+    props.put(Property.TABLE_SCAN_DISPATCHER_OPTS.getKey() + "executor.se1p1", "se1");
+    props.put(Property.TABLE_SCAN_DISPATCHER_OPTS.getKey() + "executor.se1p2", "se1");
+    props.put(Property.TABLE_SCAN_DISPATCHER_OPTS.getKey() + "executor.se2p1", "se2");
```
Comment (keith-turner) [inline src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java:100]: If we just set the executor property then that will be the default for all scan types, so do not need to set it twice.  When scan_type equals dedicated, it will override it to se2.

```suggestion
    props.put(Property.TABLE_SCAN_DISPATCHER_OPTS.getKey() + "executor", "se1");
    props.put(Property.TABLE_SCAN_DISPATCHER_OPTS.getKey() + "executor.dedicated", "se2");
```

Comment (DomGarguilo) [reply src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java]: In the test, se1 is used at two different priorities though so I thought we would need to define two scan types: se1 with priority 1 and the other se1 with priority 2. @keith-turner

Comment (keith-turner) [reply src/main/java/org/apache/accumulo/testing/performance/tests/ScanExecutorPT.java]: Yeah you do need two scan types.  This per table dispatcher does not care about prio, it just dispatches scans to the executor se1 or se2.  The executor se1 has further config that sets the prio based on scan type, which is where the two diff scan types matter.  So we have it dispatch everything to executor se1 unless the scan type is dedicated in which case it dispatches to se2.

**Comment by DomGarguilo** [comment]
> Changes look good. The test completes as expected. I did notice a few small corrections to make with other parts of the test but I will wait until you push your other changes up just in case they are already handled.

@Manno15, I included the other changes I had in mind in da3635d. Let me know if you have some more improvements.
