### PR TITLE
Fix #120 Support non default absolute hdfs paths in cingest bulk

### LINKED ISSUE #120: Support non default HDFS path as a parameter for continuous bulk ingest
Support non default HDFS (in case of multiple volumes) path as a parameter for continuous bulk ingest. For e.g
`bin/cingest bulk abfs://data@azaccumulo.dfs.core.windows.net/azbulk-multi` 

In this case `abfs://data@azaccumulo.dfs.core.windows.net/`  HDFS filesystem is not the default HDFS and has been added as a additional volume to accumulo
The default HDFS fileystem configured is `hdfs://accucluster`

`Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: abfs://data@azaccumulo.dfs.core.windows.net/azbulk-multi, expected: hdfs://accucluster:8020`

### PR DESCRIPTION
**Pull request by mandarinamdar**
Support non default and/or absolute hdfs paths in continuous bulk ingestion

* Accept non default/absolute hdfs paths too as a parameter to cingest bulk
* Without this change, only defaultFS works
* Without this change, it gives error for any parameter other than relative path
* This feature support is critical, especially in case of multiple hdfs volumes

### CODE REVIEW

File: src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java [hunk 1]
```diff
@@ -50,13 +51,14 @@
...
     String ingestInstanceId = UUID.randomUUID().toString();
+    String bulkPath = args[0];
 
     Job job = Job.getInstance(getConf());
     job.setJobName("BulkIngest_" + ingestInstanceId);
     job.setJarByClass(BulkIngest.class);
     // very important to prevent guava conflicts
     job.getConfiguration().set("mapreduce.job.classloader", "true");
-    FileSystem fs = FileSystem.get(job.getConfiguration());
+    FileSystem fs = FileSystem.get(URI.create(bulkPath), job.getConfiguration());
```
Comment (keith-turner) [inline src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java]: Do you know if paths w/o a scheme like `/tmp/bt/1` still work?

File: src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java [hunk 2]
```diff
@@ -76,7 +78,8 @@ public int run(String[] args) throws Exception {
 
       // output RFiles for the import
       job.setOutputFormatClass(AccumuloFileOutputFormat.class);
-      AccumuloFileOutputFormat.configure().outputPath(new Path(bulkDir + "/files")).store(job);
+      AccumuloFileOutputFormat.configure().outputPath(new Path(fs.getUri() + bulkDir + "/files"))
```
Comment (keith-turner) [inline src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java]: With the following, may not need `bulkDir`.  I think the `makeQualified` fuction only prefixes the fs URI if its not there.

```suggestion
      AccumuloFileOutputFormat.configure().outputPath(fs.makeQualified(new Path(bulkPath + "/files")))
```

File: src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java (hunk 1 above)
Comment (mandarinamdar) [reply src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java]: @keith-turner , thanks for reviewing. Yes, it works w/o scheme, with (default or otherwise) scheme as well

File: src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java (hunk 2 above)
Comment (mandarinamdar) [reply src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java]: I will modify and check

Comment (mandarinamdar) [reply src/main/java/org/apache/accumulo/testing/continuous/BulkIngest.java]: I have changed the code to use fs.makeQualified consistently and reuse existing bulkDir variable avoiding new variable bulkPath
